### ISSUE TITLE
Support for MongoDB 3.0

### ISSUE THREAD

**Issue by jheander** [aboekhoff/congomongo#140]
Hi,

MongoDB 3.0 is out with its second patch release and is looking more and more ready for production. It's probably best to upgrade congomongo's java driver all the way to 3.0 to be forward compatible.

All the best!
Johan

**Comment by seancorfield** [comment]
I've been keeping an eye on the various release notices for all the drivers and contemplating a move to 3.0 but haven't had the time yet to dedicate to dealing with the API changes that have been discussed. This ticket will be a good placeholder for a reminder to do that at some point.

**Comment by shinych** [comment]
Hello guys, any plans to upgrade to support MongoDB 3.0? Thank you!

**Comment by seancorfield** [comment]
The current version supports MongoDB 3.0 database but we don't yet support the 3.0 driver. Looking at PRs from CircleCI to add that. It will be an API change for the new authentication model so watch for an 0.5.0 release in the next few weeks.

**Comment by jheander** [comment]
An option in the meantime might be to upgrade to the 2.14.0 driver since it seems to be API compatible but while still supporting some of the new features. See https://github.com/mongodb/mongo-java-driver/releases

**Comment by seancorfield** [comment]
I had a ticket open for an update to the 2.12.5 driver but I've updated that to 2.14.0 now.

**Comment by seancorfield** [comment]
Release 0.4.7 includes the 2.14.0 driver and has been tested against MongoDB 3.0.

**Comment by jheander** [comment]
Thanks!
