### ISSUE TITLE
fetch doesn't return embedded documents fields in the actual order

### ISSUE THREAD

**Issue by xavi** [aboekhoff/congomongo#146]
The order of fields in embedded documents is significant for equality matching to work. MongoDB [docs say](https://docs.mongodb.org/manual/tutorial/query-documents/#exact-match-on-the-embedded-document): "Equality matches on an embedded document require an exact match of the specified \<value\>, including the field order."

But the order of fields in embedded documents as returned by `somnium.congomongo/fetch` doesn't match the actual order:

```
(m/with-mongo conn (m/fetch :sessions :where {:embedded_test {:a "4" :b "5"}}))
;; => ({:embedded_test {:b "5", :a "4"}, :_id #object[org.bson.types.ObjectId 0x2057e5d3 "570e9b226588b6feb16d06bf"]})
(m/with-mongo conn (m/fetch :sessions :where {:embedded_test {:b "5" :a "4"}}))
;; => ()
(m/with-mongo conn (m/fetch :sessions :where {:embedded_test (array-map :a "4" :b "5")}))
;; => ({:embedded_test {:b "5", :a "4"}, :_id #object[org.bson.types.ObjectId 0x330428d4 "570e9b226588b6feb16d06bf"]})
(m/with-mongo conn (m/fetch :sessions :where {:embedded_test (array-map :b "5" :a "4")}))
;; => ()
```
I assume the actual order is  `{:a "4" :b "5"}` because the document is retrieved only when querying with the fields in that order, using both regular maps or array maps. Besides, the mongo shell also shows them in that order

```
db.sessions.find()
// => { "_id" : ObjectId("570e9b226588b6feb16d06bf"), "embedded_test" : { "a" : "4", "b" : "5" } }
```

**Comment by seancorfield** [comment]
You can query on `{:embedded_test.a "4" :embedded_test.b "5"}` and you can also construct a `dbobject` (in `somnium.congomongo.coerce`) which keeps fields in order.

**Comment by xavi** [comment]
Ok, but my point is...

```
(def s (m/with-mongo conn (m/fetch-one :sessions)))
s
; => {:embedded_test {:b "5", :a "4"}, :_id #object[org.bson.types.ObjectId 0x2e63034c "570e9b226588b6feb16d06bf"]}
(m/with-mongo conn (m/fetch :sessions :where s))
; => ()
```

I think this is unexpected at the least.

In the MongoDB shell, the equivalent example works as expected...

```
s = db.sessions.findOne()
// {
// 	"_id" : ObjectId("570e9b226588b6feb16d06bf"),
// 	"embedded_test" : {
// 		"a" : "4",
// 		"b" : "5"
// 	}
// }
db.sessions.find(s)
// { "_id" : ObjectId("570e9b226588b6feb16d06bf"), "embedded_test" : { "a" : "4", "b" : "5" } }

**Comment by seancorfield** [comment]
I think you're the first person to find it surprising: Clojure hash maps are unordered by design and you're getting a Clojure data structure back.

**Comment by xavi** [comment]
I was thinking that maybe Congomongo could return documents as `array-map`s with the keys ordered as in the database. This would get rid of the (for me at least!) gotcha and would be consistent with MongoDB shell behavior.

Anyway, I just wanted to raise a possible issue.

Thanks.

**Comment by seancorfield** [comment]
I'll take a look at the implications of that next week when I get back from Clojure/West.

**Comment by seancorfield** [comment]
It looks like any change to this will impact both directions in the MongoDB / Clojure coercions and have potential performance impacts. I don't have the bandwidth / time right now to set up benchmarks and do the level of analysis necessary to figure out exactly what would need to change and how to do it without impacting performance -- it's certainly a non-trivial change. Bottom line: not going to happen in the foreseeable future.
