### ISSUE TITLE
Is connection pooling relevant with congomongo?

### ISSUE THREAD

**Issue by Engelberg** [aboekhoff/congomongo#150]
I'm trying to troubleshoot a performance issue, and mlab (cloud mongo provider) said I should make sure I'm using connection pooling, and pointed me at this article:
https://blog.mlab.com/2013/11/deep-dive-into-connection-pooling/

I'm using congomongo.  Is this relevant?

**Comment by seancorfield** [comment]
If you call `make-connection` just once at application startup and reuse that connection everywhere, then you're benefitting from connection pooling. Does that answer your question?

**Comment by Engelberg** [comment]
Yes, that is what I was hoping.  Thanks for the fast response.
